/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoeditingRouteImport } from './routes/videoediting'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BookacallRouteImport } from './routes/bookacall'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutusRouteImport } from './routes/aboutus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as SettingsWebsiteRouteImport } from './routes/settings.website'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsCallsRouteImport } from './routes/settings.calls'
import { Route as SettingsAvailabilityRouteImport } from './routes/settings.availability'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAnalyticsRouteImport } from './routes/settings.analytics'
import { Route as SettingsAdminsRouteImport } from './routes/settings.admins'
import { Route as CrmSplatRouteImport } from './routes/crm.$'
import { Route as DocKindTokenRouteImport } from './routes/doc.$kind.$token'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicTimeRouteImport } from './routes/api/public/time'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicHooksBookingRemindersRouteImport } from './routes/api/public/hooks/booking-reminders'

const VideoeditingRoute = VideoeditingRouteImport.update({
  id: '/videoediting',
  path: '/videoediting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BookacallRoute = BookacallRouteImport.update({
  id: '/bookacall',
  path: '/bookacall',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusRoute = AboutusRouteImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebsiteRoute = SettingsWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCallsRoute = SettingsCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAvailabilityRoute = SettingsAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAnalyticsRoute = SettingsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdminsRoute = SettingsAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SettingsRoute,
} as any)
const CrmSplatRoute = CrmSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CrmRoute,
} as any)
const DocKindTokenRoute = DocKindTokenRouteImport.update({
  id: '/doc/$kind/$token',
  path: '/doc/$kind/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTimeRoute = ApiPublicTimeRouteImport.update({
  id: '/api/public/time',
  path: '/api/public/time',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBookingRemindersRoute =
  ApiPublicHooksBookingRemindersRouteImport.update({
    id: '/api/public/hooks/booking-reminders',
    path: '/api/public/hooks/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/app': typeof AppRoute
  '/bookacall': typeof BookacallRoute
  '/crm': typeof CrmRouteWithChildren
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRouteWithChildren
  '/videoediting': typeof VideoeditingRoute
  '/crm/$': typeof CrmSplatRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/website': typeof SettingsWebsiteRoute
  '/sign/$token': typeof SignTokenRoute
  '/crm/': typeof CrmIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/doc/$kind/$token': typeof DocKindTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/app': typeof AppRoute
  '/bookacall': typeof BookacallRoute
  '/design': typeof DesignRoute
  '/videoediting': typeof VideoeditingRoute
  '/crm/$': typeof CrmSplatRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/website': typeof SettingsWebsiteRoute
  '/sign/$token': typeof SignTokenRoute
  '/crm': typeof CrmIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/doc/$kind/$token': typeof DocKindTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/app': typeof AppRoute
  '/bookacall': typeof BookacallRoute
  '/crm': typeof CrmRouteWithChildren
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRouteWithChildren
  '/videoediting': typeof VideoeditingRoute
  '/crm/$': typeof CrmSplatRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/calls': typeof SettingsCallsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/website': typeof SettingsWebsiteRoute
  '/sign/$token': typeof SignTokenRoute
  '/crm/': typeof CrmIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/doc/$kind/$token': typeof DocKindTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/app'
    | '/bookacall'
    | '/crm'
    | '/design'
    | '/settings'
    | '/videoediting'
    | '/crm/$'
    | '/settings/admins'
    | '/settings/analytics'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/calls'
    | '/settings/connections'
    | '/settings/website'
    | '/sign/$token'
    | '/crm/'
    | '/settings/'
    | '/api/public/time'
    | '/api/public/track'
    | '/doc/$kind/$token'
    | '/api/public/hooks/booking-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/app'
    | '/bookacall'
    | '/design'
    | '/videoediting'
    | '/crm/$'
    | '/settings/admins'
    | '/settings/analytics'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/calls'
    | '/settings/connections'
    | '/settings/website'
    | '/sign/$token'
    | '/crm'
    | '/settings'
    | '/api/public/time'
    | '/api/public/track'
    | '/doc/$kind/$token'
    | '/api/public/hooks/booking-reminders'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/app'
    | '/bookacall'
    | '/crm'
    | '/design'
    | '/settings'
    | '/videoediting'
    | '/crm/$'
    | '/settings/admins'
    | '/settings/analytics'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/calls'
    | '/settings/connections'
    | '/settings/website'
    | '/sign/$token'
    | '/crm/'
    | '/settings/'
    | '/api/public/time'
    | '/api/public/track'
    | '/doc/$kind/$token'
    | '/api/public/hooks/booking-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusRoute: typeof AboutusRoute
  AppRoute: typeof AppRoute
  BookacallRoute: typeof BookacallRoute
  CrmRoute: typeof CrmRouteWithChildren
  DesignRoute: typeof DesignRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  VideoeditingRoute: typeof VideoeditingRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiPublicTimeRoute: typeof ApiPublicTimeRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  DocKindTokenRoute: typeof DocKindTokenRoute
  ApiPublicHooksBookingRemindersRoute: typeof ApiPublicHooksBookingRemindersRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videoediting': {
      id: '/videoediting'
      path: '/videoediting'
      fullPath: '/videoediting'
      preLoaderRoute: typeof VideoeditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookacall': {
      id: '/bookacall'
      path: '/bookacall'
      fullPath: '/bookacall'
      preLoaderRoute: typeof BookacallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/website': {
      id: '/settings/website'
      path: '/website'
      fullPath: '/settings/website'
      preLoaderRoute: typeof SettingsWebsiteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calls': {
      id: '/settings/calls'
      path: '/calls'
      fullPath: '/settings/calls'
      preLoaderRoute: typeof SettingsCallsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/availability': {
      id: '/settings/availability'
      path: '/availability'
      fullPath: '/settings/availability'
      preLoaderRoute: typeof SettingsAvailabilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/analytics': {
      id: '/settings/analytics'
      path: '/analytics'
      fullPath: '/settings/analytics'
      preLoaderRoute: typeof SettingsAnalyticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/admins': {
      id: '/settings/admins'
      path: '/admins'
      fullPath: '/settings/admins'
      preLoaderRoute: typeof SettingsAdminsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/crm/$': {
      id: '/crm/$'
      path: '/$'
      fullPath: '/crm/$'
      preLoaderRoute: typeof CrmSplatRouteImport
      parentRoute: typeof CrmRoute
    }
    '/doc/$kind/$token': {
      id: '/doc/$kind/$token'
      path: '/doc/$kind/$token'
      fullPath: '/doc/$kind/$token'
      preLoaderRoute: typeof DocKindTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/time': {
      id: '/api/public/time'
      path: '/api/public/time'
      fullPath: '/api/public/time'
      preLoaderRoute: typeof ApiPublicTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/booking-reminders': {
      id: '/api/public/hooks/booking-reminders'
      path: '/api/public/hooks/booking-reminders'
      fullPath: '/api/public/hooks/booking-reminders'
      preLoaderRoute: typeof ApiPublicHooksBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmSplatRoute: typeof CrmSplatRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmSplatRoute: CrmSplatRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface SettingsRouteChildren {
  SettingsAdminsRoute: typeof SettingsAdminsRoute
  SettingsAnalyticsRoute: typeof SettingsAnalyticsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAvailabilityRoute: typeof SettingsAvailabilityRoute
  SettingsCallsRoute: typeof SettingsCallsRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsWebsiteRoute: typeof SettingsWebsiteRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdminsRoute: SettingsAdminsRoute,
  SettingsAnalyticsRoute: SettingsAnalyticsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAvailabilityRoute: SettingsAvailabilityRoute,
  SettingsCallsRoute: SettingsCallsRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsWebsiteRoute: SettingsWebsiteRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusRoute: AboutusRoute,
  AppRoute: AppRoute,
  BookacallRoute: BookacallRoute,
  CrmRoute: CrmRouteWithChildren,
  DesignRoute: DesignRoute,
  SettingsRoute: SettingsRouteWithChildren,
  VideoeditingRoute: VideoeditingRoute,
  SignTokenRoute: SignTokenRoute,
  ApiPublicTimeRoute: ApiPublicTimeRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  DocKindTokenRoute: DocKindTokenRoute,
  ApiPublicHooksBookingRemindersRoute: ApiPublicHooksBookingRemindersRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
