/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonteurRouteImport } from './routes/monteur'
import { Route as ImmobilierRouteImport } from './routes/immobilier'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonteurIndexRouteImport } from './routes/monteur.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MonteurProjetsRouteImport } from './routes/monteur.projets'
import { Route as MonteurParametresRouteImport } from './routes/monteur.parametres'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminProjetsRouteImport } from './routes/admin.projets'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminMonteursRouteImport } from './routes/admin.monteurs'
import { Route as AdminDevisRouteImport } from './routes/admin.devis'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAvisRouteImport } from './routes/admin.avis'
import { Route as AdminAnalytiquesRouteImport } from './routes/admin.analytiques'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const MonteurRoute = MonteurRouteImport.update({
  id: '/monteur',
  path: '/monteur',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobilierRoute = ImmobilierRouteImport.update({
  id: '/immobilier',
  path: '/immobilier',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteurIndexRoute = MonteurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonteurRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MonteurProjetsRoute = MonteurProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => MonteurRoute,
} as any)
const MonteurParametresRoute = MonteurParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => MonteurRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonteursRoute = AdminMonteursRouteImport.update({
  id: '/monteurs',
  path: '/monteurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisRoute = AdminAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalytiquesRoute = AdminAnalytiquesRouteImport.update({
  id: '/analytiques',
  path: '/analytiques',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/crm': typeof CrmRoute
  '/immobilier': typeof ImmobilierRoute
  '/monteur': typeof MonteurRouteWithChildren
  '/admin/analytiques': typeof AdminAnalytiquesRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/monteurs': typeof AdminMonteursRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/monteur/parametres': typeof MonteurParametresRoute
  '/monteur/projets': typeof MonteurProjetsRoute
  '/admin/': typeof AdminIndexRoute
  '/monteur/': typeof MonteurIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/crm': typeof CrmRoute
  '/immobilier': typeof ImmobilierRoute
  '/admin/analytiques': typeof AdminAnalytiquesRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/monteurs': typeof AdminMonteursRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/monteur/parametres': typeof MonteurParametresRoute
  '/monteur/projets': typeof MonteurProjetsRoute
  '/admin': typeof AdminIndexRoute
  '/monteur': typeof MonteurIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/crm': typeof CrmRoute
  '/immobilier': typeof ImmobilierRoute
  '/monteur': typeof MonteurRouteWithChildren
  '/admin/analytiques': typeof AdminAnalytiquesRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/monteurs': typeof AdminMonteursRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/monteur/parametres': typeof MonteurParametresRoute
  '/monteur/projets': typeof MonteurProjetsRoute
  '/admin/': typeof AdminIndexRoute
  '/monteur/': typeof MonteurIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/crm'
    | '/immobilier'
    | '/monteur'
    | '/admin/analytiques'
    | '/admin/avis'
    | '/admin/clients'
    | '/admin/devis'
    | '/admin/monteurs'
    | '/admin/parametres'
    | '/admin/projets'
    | '/admin/videos'
    | '/monteur/parametres'
    | '/monteur/projets'
    | '/admin/'
    | '/monteur/'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/crm'
    | '/immobilier'
    | '/admin/analytiques'
    | '/admin/avis'
    | '/admin/clients'
    | '/admin/devis'
    | '/admin/monteurs'
    | '/admin/parametres'
    | '/admin/projets'
    | '/admin/videos'
    | '/monteur/parametres'
    | '/monteur/projets'
    | '/admin'
    | '/monteur'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/crm'
    | '/immobilier'
    | '/monteur'
    | '/admin/analytiques'
    | '/admin/avis'
    | '/admin/clients'
    | '/admin/devis'
    | '/admin/monteurs'
    | '/admin/parametres'
    | '/admin/projets'
    | '/admin/videos'
    | '/monteur/parametres'
    | '/monteur/projets'
    | '/admin/'
    | '/monteur/'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  CrmRoute: typeof CrmRoute
  ImmobilierRoute: typeof ImmobilierRoute
  MonteurRoute: typeof MonteurRouteWithChildren
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monteur': {
      id: '/monteur'
      path: '/monteur'
      fullPath: '/monteur'
      preLoaderRoute: typeof MonteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobilier': {
      id: '/immobilier'
      path: '/immobilier'
      fullPath: '/immobilier'
      preLoaderRoute: typeof ImmobilierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monteur/': {
      id: '/monteur/'
      path: '/'
      fullPath: '/monteur/'
      preLoaderRoute: typeof MonteurIndexRouteImport
      parentRoute: typeof MonteurRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/monteur/projets': {
      id: '/monteur/projets'
      path: '/projets'
      fullPath: '/monteur/projets'
      preLoaderRoute: typeof MonteurProjetsRouteImport
      parentRoute: typeof MonteurRoute
    }
    '/monteur/parametres': {
      id: '/monteur/parametres'
      path: '/parametres'
      fullPath: '/monteur/parametres'
      preLoaderRoute: typeof MonteurParametresRouteImport
      parentRoute: typeof MonteurRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monteurs': {
      id: '/admin/monteurs'
      path: '/monteurs'
      fullPath: '/admin/monteurs'
      preLoaderRoute: typeof AdminMonteursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avis': {
      id: '/admin/avis'
      path: '/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AdminAvisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytiques': {
      id: '/admin/analytiques'
      path: '/analytiques'
      fullPath: '/admin/analytiques'
      preLoaderRoute: typeof AdminAnalytiquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalytiquesRoute: typeof AdminAnalytiquesRoute
  AdminAvisRoute: typeof AdminAvisRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDevisRoute: typeof AdminDevisRoute
  AdminMonteursRoute: typeof AdminMonteursRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalytiquesRoute: AdminAnalytiquesRoute,
  AdminAvisRoute: AdminAvisRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDevisRoute: AdminDevisRoute,
  AdminMonteursRoute: AdminMonteursRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MonteurRouteChildren {
  MonteurParametresRoute: typeof MonteurParametresRoute
  MonteurProjetsRoute: typeof MonteurProjetsRoute
  MonteurIndexRoute: typeof MonteurIndexRoute
}

const MonteurRouteChildren: MonteurRouteChildren = {
  MonteurParametresRoute: MonteurParametresRoute,
  MonteurProjetsRoute: MonteurProjetsRoute,
  MonteurIndexRoute: MonteurIndexRoute,
}

const MonteurRouteWithChildren =
  MonteurRoute._addFileChildren(MonteurRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  CrmRoute: CrmRoute,
  ImmobilierRoute: ImmobilierRoute,
  MonteurRoute: MonteurRouteWithChildren,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
